www/templates/foundation/members/index.html
The names were slightly off from what we documented in the governance. Updated!
=> Correcting the names

www/fixtures/faq.yaml, www/templates/index.html
Lots of outdated references to CloudLinux. Removed and/or updated them to reflect current reality. 
Signed-off-by: benny Vasquez <bvasquez@chef.io>
=> updated/removed outdated content leftover from the AlmaLinux launch.

Dockerfile, Dockerfile-frontend, frontend/src/modules/page_contribute/main.scss, frontend/src/modules/page_foundation/main.js, frontend/src/modules/page_foundation/main.scss, frontend/src/modules/page_page/main.scss, www/templates/contribute/index.html, www/templates/foundation/members/index.html
https://github.com/AlmaLinux/almalinux.org/issues/34 //done
Then https://github.com/AlmaLinux/almalinux.org/issues/35 https://github.com/AlmaLinux/almalinux.org/issues/35 //done
Then https://github.com/AlmaLinux/almalinux.org/issues/36 https://github.com/AlmaLinux/almalinux.org/issues/36 //done
Then https://github.com/AlmaLinux/almalinux.org/issues/37 https://github.com/AlmaLinux/almalinux.org/issues/37 //done
=> [ADD] added membership info, added doc links

Dockerfile, Dockerfile-frontend, frontend/src/modules/page_contribute/main.scss, frontend/src/modules/page_foundation/main.js, frontend/src/modules/page_foundation/main.scss, frontend/src/modules/page_page/main.scss, www/templates/contribute/index.html, www/templates/foundation/members/index.html
https://github.com/AlmaLinux/almalinux.org/issues/22
Done
=> CURRENT_GID on mac might render incompatible with a Linux container

Dockerfile, Dockerfile-frontend, frontend/src/modules/page_contribute/main.scss, frontend/src/modules/page_foundation/main.js, frontend/src/modules/page_foundation/main.scss, frontend/src/modules/page_page/main.scss, www/templates/_partial/footer.html, www/templates/contribute/index.html, www/templates/foundation/members/index.html
=> Almalinux issue 03

www/templates/contribute/index.html
=> make relative link of foundation members

frontend/src/modules/page_blog/main.scss, www/templates/blog/post.html, www/views.py
=> [ADD] Blog post new/older links #19

frontend/src/common/scss/main.scss, frontend/src/modules/page_certified/main.scss, frontend/src/modules/page_index/main.scss, www/templates/blog/index.html, www/templates/blog/post.html, www/templates/index.html
=> perform a11y review and fix its issue

www/admin.py
Commented debug statement, resolves #54
=> Remove debug code, Fix#54

www/templates/blog/index.html, www/templates/layouts/base.html
=> added rss feed button on blog page

www/templates/blog/index.html
the default profile image name on the blog page is changed.
=> fix the broken blog profile image

www/templates/index.html
Removing the form and pushing folks to our mailing lists for now.
=> The form on this was funneling to /dev/null. 

www/templates/sbom/index.html, www/urls.py, www/views.py
add index file for sbom page. edit urls.py and views.py
=> add sbom page

.github/workflows/publish.yml, layouts/index.html
=> WIP: More localization updates

layouts/blog/list.html, layouts/index.html, layouts/partials/common/nav.html, layouts/partials/common/scripts.html
This is the code from @sakelestemur's `almalinux-responsive` archive.
Just fixed a couple of trailing spaces, empty lines, etc. 
Side note:
We probably need to clean up the html as `tidy` reports a bunch of errors.
=> Changes from Atalay.

layouts/index.html
An attempt to fix the problem outlined in #167. Only adjusting a small thing in the code that has been bugging me.
=> committing a small change to trigger a website rebuild.

assets/css/bundle.css, assets/scss/blog.css, assets/scss/blog.scss, assets/scss/main.css, assets/scss/main.scss, layouts/blog/list.html, layouts/blog/single.html
600px wide is way too thin.  the rest of the site is limited to 1320px by the `.container` element so this PR makes the blog width also inherit that limit.
=> increase width of blog content

content/blog/impact-of-rhel-changes.md
Adding a link to last week's blog that points new folks to the update as well.
=> Adding a new link to the update blog from last week's.

layouts/blog/list.html
=> Fix x-overflow in blog section

layouts/blog/single.html
forgot to add some changes in #234
=> fix x-overflow in single.html

find_missing_i18n_strings.py
Haven't tested this with CI yet. 
Addresses https://github.com/AlmaLinux/almalinux.org/issues/250
=> Populate missing i18n keys in en.json, print unused i18n keys

assets/css/bundle.css, assets/scss/blog.css, assets/scss/blog.scss, config.yaml, content/blog/zenbleed-patch-call-for-testing.md
Reverts AlmaLinux/almalinux.org#272
=> Revert "Clean up blog syntax a bit, add code highlighting config"

layouts/blog/list.html, layouts/blog/single.html
This is also to test new CI workflow to create preview sites from fork PRs.
=> make blog permalinks relative

content/p/the-almalinux-os-licensing-policy.md
This is an attempt to make licensing decisions easier for contributors, but isn't new information.
=> Adding licensing guidance for contributors.

layouts/index.html
and removed one company no longer sponsoring.
=> updated sponsor order to reflect levels

layouts/ato-2023/single.html, layouts/index.html
This includes code improvements for the top picture and fixed mobile version for the ELevate scheme picture. Also removed a typo in the security section.
=> Additional changes to ATO and main pages

i18n/en.json, i18n/es.json, i18n/ja.json, i18n/sv.json, layouts/aldt-2023/single.html
=> fix typo: lidabashi -> Iidabashi

layouts/get-almalinux/single.html
Note: please merge when torrent files are available
=> Updated the page with AlmaLinux 8.9 links and cheksums

i18n/en.json, layouts/aldt-2023/single.html
@bennyvasquez Translations will be done later on Weblate.
=> ALDT: Update session titles and speakers

CONTRIBUTING.md
@codyro everything look good to you?
=> updating the blog template to include the new social image bit.

layouts/get-almalinux/single.html
PR #410 brought to light this typo.
=> fixing a typo

content/p/membership-committee.md
Updates to the membership committee guidance. Approved by the committee and the board.
=> Updating the membership committee guidance

i18n/en.json, layouts/aldt-2023/single.html, layouts/ato-2023/single.html, layouts/index.html
Updating URLs and branding for CTJ and MIRACLE LINUX
=> Various updates

content/blog/almalinux-live-media-and-cloud-images-85-updates.md, content/blog/almalinux-now-available-on-microsoft-azure-azure-sponsors-almalinux.md
Fixing Azure Marketplace links for AlmaLinux images.
=> Fixing Azure Marketplace links for AlmaLinux images.

layouts/get-almalinux/single.html
Simplifying the code on the Download page - reworked anchor links on icon buttons for all AlmaLinux arches and options.
=> Simplifying thee Download's page code

README.md, contributing-blog-posts.md
It isn't at all clear how one might suggest a design or content update for the website, and some of our general contribution questions were never answered here. This PR expands the contribution guidelines to include how to suggest code or design updates, and adds more information about translation contributions as well, supplementing what we already had in place for contributing blog posts.
=> expanding contribution information

.github/workflows/publish-preview.yml, .github/workflows/publish.yml
=> update checkout action to v4 (nodejs 20)

i18n/en.json, layouts/almalinux-day-germany-2024/single.html
Fixed the time of the board presentation, and also removed a bunch of commented-out-and-no-longer-needed code.
=> Fixing the times of the presentations

content/blog/2024-04-02-xz-and-cve-2024-1086.md
=> fix broken link to chat.almalinux.org

assets/css/bundle.css, i18n/en.json, layouts/partials/common/footer.html
Adding a note to make sure we comply with this: https://www.irs.gov/charities-non-profits/solicitation-notice
=> Another small change to the footer

_redirects
=> Add redirect to account for /<lang>/contribute

i18n/en.json, layouts/get-almalinux/single.html
When reviewing translations today I noticed that there were some extra entries in the translations that indicated typos in the files. This PR fixes those.
=> Fixed a typo that was causing a translation error.

content/blog/2024-04-22-why-I-wanted-to-help-translating-the-AlmaLinux-website-to-Hebrew.md
=> Add OpenGraph image to Noam's post

i18n/en.json, layouts/get-almalinux/single.html, layouts/partials/common/nav.html
-Updated banner 
-Updated links and sha on Get AlmaLinux page
=> Updates for AlmaLinux 9.4 stable

i18n/en.json, layouts/security/single.html
-Added third signed certificate 
-Adjusted to display all three correctly
=> Added third Secure Boot Certificate

content/blog/2024-05-23-mythbusting-linux-on-azure.md
Adding the video to today's webinar post, along with the deck in PDF format.
Thanks to @Noam-Alum and @mattlasheboro, the video embeds perfectly. <3
=> Add azure webinar video

content/blog/2023-12-14-2023-highlights.md, content/blog/2024-01-16-video-contributions.md, content/blog/2024-02-01-aldt-recap.md, content/blog/2024-02-29-feb-event-recap.md, content/blog/2024-05-01-almalinux-day-germany-recap.md, content/blog/2024-05-06-announcing-94-stable.md, content/blog/2024-05-28-announcing-810-stable.md
Fixed YouTube embedded videos titles and changed `2024-05-28-announcing-810-stable.md` to use the shortcode.
https://github.com/AlmaLinux/almalinux.org/issues/572
=> Fixed YouTube embedded videos titles and changed 2024-05-28-announcing-810-stable.md to use the shortcode

layouts/amd-ryzen-may2022/single.html
=> remove extra character

content/blog/2024-07-25-testing-glibc-needed.md
Forgot to sync the changes I'd made in the draft to the PR.
=> updating text

assets/css/bundle.css, layouts/index.html, layouts/partials/common/newsletter.html
These are some adjustments to fix **Community** and **Commercial Support** sections
=> Adjustments for responsive design

layouts/aldt-2023/single.html, layouts/alesco/single.html, layouts/almalinux-day-germany-2024/single.html, layouts/elevate/single.html
I made a CSS change that broke buttons on historical pages. Brought the older pages in line with the new phrasing
=> Fixing buttons

_redirects, layouts/index.html
We're working on some social media stuff that had me reviewing the FAQs and I realized they could be phrased better. I also need two redirects put in place for same social media stuff. I'm not positive that the note will carry offer and not cause problems in deploying, so @codyro and @jonathanspw I'll need y'all to take a look at that.
=> Updating the FAQs and adding a couple redirects

content/blog/2024-10-23-join-the-alesco-meetup.md
=> Fix typo in ALESCo Live Q&A Blog

content/blog/2024-10-24-almalinux-at-ato.md
Was WAY too focused on the t-shirts here and completely forgot to include the talks. :D
=> Adding my talks to the blog post 🤦 

layouts/certification/ecosystem-catalog/single.html, layouts/certification/hardware-certification/list.html, layouts/certification/list.html, layouts/certification/software-certification/list.html
Newly added pages were missing relLangURL.
=> add missing relLangURL to i18n links

content/blog/2024-12-09-welcome-to-aldt.md, i18n/en.json, layouts/aldt-2024/single.html
Slight tweaks for the schedule
=> ALDT schedule update

layouts/aldt-2023/single.html, layouts/aldt-2024/single.html, layouts/almalinux-day-germany-2024/single.html, layouts/ato-2023/single.html, layouts/index.html
OpenLogic has opted not to renew this year. Removing them and fixing some formatting stuff.
=> adjusting sponsors

content/blog/2024-10-22-introducing-almalinux-os-kitten.md
We want to direct people to the right place to give feedback.
=> Update AlmaLinux OS Kitten 10 announcement with link to x86_64-v2 RFC

README.md
Didn't catch that I was adding a recursive link when copying it before. Decided this should link to the wiki anyway. :D
=> Fix recursive link to point to the wiki

static/images/icon.svg
Turns out this was 2 pixels short of square. Fixing that.
=> making our SVG icon square

content/blog/2025-04-24-election-announcement.md
- Points towards Wiki minutes page/anchor now
=> Fix hyperlink in 2025 election blog post

README.md
This PR improves the clarity, consistency, and formatting of the README.md file. 
It simplifies wording, ensures consistent technical terminology, and improves readability.
=> Improve README.md clarity, consistency, and formatting

layouts/security/single.html
We need to not use the MIT keyserver as it's loaded for me once since I was 16, and even then it struggled. We probably should also rotato potato it to `keys.openpgp.org`. That's for another issue, though.
Preview URL (updated): https://b9ccde69.almalinux-org.pages.dev/security/
```bash
[root@682a3a2bf318 ~]# curl -s https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux-10
-----BEGIN PGP PUBLIC KEY BLOCK-----
mQINBGaP6O8BEACvg8IlAxGayV8zOi9Ex+Pd8lrj2BrBzloG8ri84ORp9o8ojq7l
ykKmIElHe11cQD2Lf/a4lcQQ4Ec3baiD786X6K2eVSlBEAnZMzfjDg8R63SfsBuu
8Yk+lUyqlBrDnSDYaPruOAzLIz2r82ikIC1jDbipZsMFPFHPI4/hayyWxJ3oGxRe
0mbtYLB9ElEKngt+/hfo7JLklakbznyIRuVEF3VrZb91XC6r/idqfJoNyBXSKidj
z0IwqOhgkLUk84rzltDo3AzwGqusd7PEuhOmqinOhp0hMdXsztD4TVyhw82iXu/O …
```
=> Update `/security` page with AL10 GPG signing key

content/blog/2025-08-06-announcing-native-nvidia-suport.md
=> Fix typo in package name
