AlmaLinux/almalinux.org

locale/ar/LC_MESSAGES/django.po
locale/ca/LC_MESSAGES/django.po
locale/cs/LC_MESSAGES/django.po
locale/da/LC_MESSAGES/django.po
locale/de/LC_MESSAGES/django.po
locale/el/LC_MESSAGES/django.po
locale/es/LC_MESSAGES/django.po
locale/fi/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/django.po
locale/he/LC_MESSAGES/django.po
locale/it/LC_MESSAGES/django.po
locale/ja/LC_MESSAGES/django.po
locale/ko/LC_MESSAGES/django.po
locale/lt/LC_MESSAGES/django.po
locale/lv/LC_MESSAGES/django.po
locale/pl/LC_MESSAGES/django.po
locale/pt/LC_MESSAGES/django.po
locale/pt_BR/LC_MESSAGES/django.po
locale/ru/LC_MESSAGES/django.po
locale/sk/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/django.po
locale/tr/LC_MESSAGES/django.po
locale/uk/LC_MESSAGES/django.po
locale/zh_Hans/LC_MESSAGES/django.po
www/templates/elevate/index.html

Since [a former PR](https://github.com/AlmaLinux/leapp-data/pull/6) has been accepted, I added appropriate mentions to the website.

Mention leapp-related EuroLinux presence

---

www/templates/_partial/navbar.html

The header is not expanded by default. It opens shrink, and the user can expand it by clicking on the relevant button.

Set sticky header shrink by default

---

www/templates/layouts/base.html

Add matomo tracking code in preparation of dropping google analytics.
It is outside of the "dnt_is_enabled" block because Matomo itself respects the DNT flag.

Add matomo tracking code

---

layouts/p/single.html

This was defaulting to `0001-01-01 00:00:00 +0000 UTC` as no `date` was in the front matter. Looking at all of the pages that use this template none require a publish date.
EX: https://almalinux.org/p/legal-notice/ vs. https://remove-publish-date-subpages.almalinux-org.pages.dev/p/legal-notice/

Remove publish date from subpages as it's unnecessary

---

assets/css/bundle.css
assets/scss/blog.css
assets/scss/blog.scss
layouts/blog/list.html

I tested https://www.almalinux.com/blog on an iPhone 12 pro and a Samsung S20, and the content is wider than the screen.
The cause was the inline CSS in the /layouts/blog/list.html
I moved the CSS into the CSS files and changed
width: 450px;
to
max-width: 100%;
This will prevent page overflow on devices with > 800px wide displays.

Fixes Page Content Overflowing on Blog on Small Displays

---

layouts/partials/common/nav.html

For some reason the a element for .dropdown-toggle had it's top margin set to 3px, while all the other menu items had theirs set to 5px.
I updated this to make it 5px across the board so that the top menu would line up on desktop browsers.
Previous:
Updated:

Changes Margin of "Resources" Drop Down

---

_redirects
layouts/index.html
layouts/partials/common/footer.html
layouts/partials/common/nav.html

This will make using the CF pages preview sites from CI easier since the links will all be relative and not send you to the live site by mistake.

Use relative localized URLs

---

assets/css/bundle.css
assets/scss/blog.css
assets/scss/blog.scss
content/blog/zenbleed-patch-call-for-testing.md

Current: https://almalinux.org/blog/zenbleed-patch-call-for-testing/
Preview: https://blog-syntax-highlighting.almalinux-org-11c.pages.dev/blog/zenbleed-patch-call-for-testing/
I believe this addresses the word wrap issues. Cleaned up a bit of the formatting as well.
@mattlasheboro helped with the CSS, so thank you!

Enable and style code syntax highlighting, adjust AMD zenbleed blog post formatting

---

config.yaml

This adjusts the default highlight style from `monokai` to `xcode-dark` which fits our theme a bit better. It didn't get included in PR #275

Add markdown / highlight configuration / use different style

---

assets/css/bundle.css
assets/scss/main.css

Fixes:
https://github.com/AlmaLinux/almalinux.org/issues/279

Make Long Links Break Into New Line Instead of Overflowing

---

assets/css/bundle.css
assets/scss/home.css
assets/scss/home.scss
layouts/index.html

Based on issue:
https://github.com/AlmaLinux/almalinux.org/issues/105

Adds TuxCare and OpenLogic blurbs

---

assets/css/bundle.css

Related Issue: #294.  
Some wide images in the blog section can overflow the display on mobile devices, introducing horizontal scrolling.  This PR addresses that.

Prevents Wide Images From Overflowing The Screen

---

content/blog/almalinux-os-brings-openqa-to-rhel.md
content/blog/future-of-almalinux.md
content/blog/new-repositories-for-almalinux-os-synergy-and-testing.md
content/blog/testers-needed-for-updated-packages-intel-and-amd-cpus-affected.md
content/blog/zenbleed-patch-call-for-testing.md
layouts/index.html

We have received a TON of feedback that folks who read our updates are confused by the 'ABI' part of what we're saying, so we're adjusting references to ABI to say 'binary' instead. This seems to be enough to assuage concerns and fix the misunderstandings when we're talking to folks, so I'm hoping this is the only change that's really needed. 
Adjusted references to ABI compatibility in all blogs that have mentioned it. Also updated the FAQ for the homepage while I was in there.

Adjust ABI phrasing.

---

content/blog/2023-09-07-almalinux-events-2023.md
content/blog/2023-09-14-election-2023.md
content/blog/2023-09-19-fips-validation-for-almalinux.md
content/blog/2023-09-26-almalinux-jupyter.md
content/blog/2023-10-26-announcing-93-beta.md
content/blog/2023-11-02-announcing-89-beta.md
content/blog/2023-11-13-announcing-93-stable.md
content/blog/2023-11-13-announcing-aldt.md
content/blog/new-repositories-for-almalinux-os-synergy-and-testing.md
content/blog/testers-needed-for-updated-packages-intel-and-amd-cpus-affected.md
content/blog/welcoming-openlogic-hawkhost-almalinux-os-foundation.md
content/blog/zenbleed-patch-call-for-testing.md
layouts/partials/common/head.html
layouts/partials/common/opengraph.html

This PR adds an Open Graph template, enabling support on all/any of the pages on the website. 
Some notes:
* Instead of using the [internal Open Graph template](https://gohugo.io/templates/internal/#use-the-open-graph-template) from Hugo, I have created a template with some modified logic for our needs (EX, serve default Open Graph image when none are detected)
* Added basic metadata to recent blog posts to serve the image in the blog post (`images[]` array in the front matter)
We need a good default image to serve if none is detected. Right now, it uses what it has been for all of these years, https://almalinux.org/images/hero.png, which is *not* ideal. @mattlasheboro can you help come up with a reasonable default image for this?

Add Open Graph support

---

layouts/aldt-2023/single.html

The Docker Hub page shouldn't be listed with the rest of our socials.

Remove Docker Hub the ALDT page social links

---

LICENSE.txt
README.md

This repo doesn't have a license associated with it, and it should. I chose CC-BY-SA-4.0 based on our [licensing policy](https://almalinux.org/p/the-almalinux-os-licensing-policy/). 
also removed the copyright line from the README

Adding a license

---

layouts/partials/common/footer.html

Currently for a reason the Resources in the footer are linked to the AlmaLinux email from our contacts, looks like it needs to be fixed

Resources no more linked to AlmaLinux email

---

layouts/_default/baseof.html

Example result:
```html
<html lang="he" dir="rtl">
```
- Refs #498

Fix template to support language direction in the config

---

layouts/ato-2023/single.html
layouts/contribute/single.html
layouts/index.html
layouts/members/single.html
layouts/partials/common/nav.html
layouts/security/single.html

Specifying a direct path causes the language selection to be lost.
e.g., https://almalinux.org/ja/contribute/ => 「会員になる」 => https://almalinux.org/members/

Use relLangURL for most href

---

content/blog/2023-12-14-2023-highlights.md
content/blog/2024-01-16-video-contributions.md
content/blog/2024-02-01-aldt-recap.md
content/blog/2024-02-29-feb-event-recap.md
content/blog/2024-05-01-almalinux-day-germany-recap.md
content/blog/2024-05-06-announcing-94-stable.md
contributing-blog-posts.md
layouts/shortcodes/youtube.html

I added a modified version of the [shortcode for YouTube embeds](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/shortcodes/youtube.html) and updated all pages using iframes to use the shortcode.
These are the pages I modified:
|Link                                                              |Changed?|
|------------------------------------------------------------------|--------|
|https://almalinux.org/blog/2023-12-14-2023-highlights/            |Yes     |
|https://almalinux.org/blog/2024-01-16-video-contributions/        |Yes     |
|https://almalinux.org/blog/2024-05-06-announcing-94-stable/       |Yes     |
|https://almalinux.org/blog/2024-05-01-almalinux-day-germany-recap/|Yes     |
|https://almalinux.org/blog/2024-02-29-feb-event-recap/            |Yes …

Added YouTube shortcode width and height functionality

---

layouts/get-almalinux/single.html

- Unified Generic Cloud links for 8.10 x86_64 since the images have hybrid boot and the download URLs of the UEFI images are symlinked to the current image (same as for 9.4)
- Updated Raspberry Pi 8 version to 8.10

Updates to the downloads page

---

layouts/index.html
layouts/partials/common/footer.html
layouts/partials/common/nav.html

Following our latest discussion with Cody, replacing the absolute links to the Get AlmaLinux page with relative. Noticed the same issue with Membership and ELevate, so also replacing them.

Replacing absolute links with relative

---

content/blog/2024-07-01-almalinux-9-CVE-2024-6387.md
content/blog/2024-07-09-cve-2024-6409.md

Got a question about what version of OpenSSH should be installed for an update because our wording wasn't clear. Updated on both of the recent OpenSSH blog posts to be more clear.

Updating wording on two blog posts for clarity

---

content/blog/_index.md

[Getting an error when](https://github.com/AlmaLinux/almalinux.org/actions/runs/11186588851/job/31105702504) attempting to publish a blog post. I was able to reproduce it locally by upgrading from Hugo 0.134.1 -> 0.135.0. Now when I build the site, I get this error:
`ERROR invalid front matter: date: %!!(MISSING)s(<nil>): see ($webroot)/content/blog/_index.md`
It looks like we're being [hit by this validation](https://github.com/gohugoio/hugo/commit/4c02a52f7c4de651394d01ff4d57d0d380c7b81a) change.  Adding date: '2021-01-01' to that file seems to have solved that error.

fix date error

---

config.yaml
layouts/blog/single.html
layouts/partials/common/opengraph.html

- **File Check Post-Render**: Removed `taxonomyterm` as noted in the [Hugo v0.116.0 release](https://github.com/gohugoio/hugo/releases/tag/v0.116.0).
- **Blog Count Pagination**: Replaced `paginate: 15` with the new `pagination` format:
```yaml
pagination:
pagerSize: 15
```
- **Social Links**: Updated to the new syntax in `layouts/partials/common/opengraph.html`.
- **Page Navigation**: Updated `.Page.PrevPage` and `.Page.NextPage` to the new syntax in `layouts/blog/single.html`.
I can't explain why, but it seems like the nav menu items look different:
- Old:
- New:
Also if I try to use the website translated (Locally) I can't access the blog's area, but this seems to be not related to the changes as I tested this on a blank clone.
@codyro If you can generate a test website (from GitHub …

Fixed deprecated warnings

---

content/blog/2024-10-07-fips-validation-for-almalinux-update.md

Just adds a footnote about the OpenSSL certificate getting delivered just after we published the blog

OpenSSL update to Noam's FIPS blog post

---

assets/css/bundle.css
layouts/get-almalinux/single.html

This should fix the current (recently appeared) situation with icons on the download page. Also to try to prevent same issues in the future I renamed their class and moved their width/height to the bundle file

Fixing icons on the download page

---

assets/css/bundle.css
layouts/index.html

The AMD and Knownhost logos under 'backers' were getting stretched, causing them to be mis-displayed. These two small changes correct the problems.
Before: 
After:

Fixing knownhost and AMD icons

---

layouts/get-almalinux/single.html

Starting 9.5 release there are also live media images available for aarch64, so I'm adding live media there too

Updating Live Media for 9.5

---

_redirects

Using almalinux.org/migrate on some marketing materials, and this will send them to the right place. There's a chance we'll make a website page to match this soon, so I'm marking it as a 307 and setting myself a reminder to re-evaluate in a few months.

Adding /migrate redirect

---

.github/workflows/publish-preview.yml
.github/workflows/publish.yml

To resolve the last hurdle for #709 - pinning to the version that was used in the [most recent deploy of the website](https://github.com/AlmaLinux/almalinux.org/actions/runs/12876094538/job/35898521829). 
Not entirely sure it's this simple, but if it is then sweet! Just need confirmation from @AlmaLinux/website-infra

Pin hugo version

---

.github/workflows/publish-preview.yml
.github/workflows/publish.yml

Updating the hugo version that we're pinned to so I can use some new features. Tested with these URLs to ensure nothing broke in our normal functionality:
http://localhost:1313/blog/
http://localhost:1313/blog/2025-04-08-announcing-96-beta/
http://localhost:1313/blog/2025-02-20-test-patches-for-cve-2025-26465/
http://localhost:1313/almalinux-day-germany-2024/
http://localhost:1313/certification/ecosystem-catalog/
http://localhost:1313/members/

updating hugo

---

content/blog/2025-09-08-enabling-crb-by-default-for-almalinux10.md

It's not relevant and it confuses people.

Drop the mention of AlmaLinux 10.1 from the enabling CRB blog post
